# Generated by Django 3.2.10 on 2022-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20220118_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='descriptionRaw',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
